on:
#  workflow_dispatch:
#    inputs:
#      targetVariable:
#        description: Env variable to be update
#        required: true
#        type: choice
#        options:
#          - TEST_1
#          - TEST_2
#      newValue:
#        description: Value to be assigned to the targeted env variable
#        required: true
#        type: string
#    env:
#      BRANCH: feature/automated_versions_bump
#      MAIN_BRANCH: main
  repository_dispatch:
    types: version-bump


name: pr-creation

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/automated_versions_bump
      - id: update-env
        run: |
          file=test.env
          sed -i 's/${{github.event.client_payload.targetVariable}}=.*/${{github.event.client_payload.targetVariable}}=${{github.event.client_payload.newValue}}/' $file
          
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "chore: bump default version for ${{github.event.client_payload.targetVariable}} to ${{github.event.client_payload.newValue}}"
          git push origin

      - uses: actions/github-script@v6
        id: open-pull-request
        with:
          script: |
            
            let res = await github.rest.pulls.list({
              owner: 'vclerc',
              repo: 'console-printer-lerna',
              state: 'open',
              head: 'vclerc:feature/automated_versions_bump',
              base: 'main'
            });
            
            if (res.data.length === 0) {
              await github.rest.pulls.create({
                owner: 'vclerc',
                repo: 'console-printer-lerna',
                title: 'Testing PR creation',
                head: 'feature/automated_versions_bump',
                base: 'main'
              });
            }