on:
  workflow_dispatch:
    inputs:
      targetVariable:
        description: Env variable to be update
        required: true
        type: choice
        options:
          - TEST_1
          - TEST_2
      newValue:
        description: Value to be assigned to the targeted env variable
        required: true
        type: string
    env:
      BRANCH: feature/automated_versions bump
      MAIN_BRANCH: main

name: pr-creation

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: env.BRANCH
      - id: update-env
        run: |
          file=test.env
          sed -i 's/${{inputs.targetVariable}}=.*/${{inputs.targetVariable}}=${{inputs.newValue}}/' $file
          
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "chore: sync packages version ${current_version}"
          git push origin
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          base: env.MAIN_BRANCH