on:
  repository_dispatch:
    types: version-bump

name: pr-creation
concurrency:
  group: version-bump
  cancel-in-progress: false

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: feature/automated_versions_bump
      - id: update-env
        run: |
          file=test.env
          sed -i 's/${{github.event.client_payload.targetVariable}}=.*/${{github.event.client_payload.targetVariable}}=${{github.event.client_payload.newValue}}/' $file
          
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "chore: bump default version for ${{github.event.client_payload.targetVariable}} to ${{github.event.client_payload.newValue}}"
          git push origin

      - uses: actions/github-script@v6
        id: open-pull-request
        with:
          env:
            BASE_BRANCH: ${{ vars.BASE_BRANCH }}
          script: |
            console.log("CONTEXT: " + $BASE_BRANCH);
            
            let res = await github.rest.pulls.list({
              owner: 'vclerc',
              repo: 'console-printer-lerna',
              state: 'open',
              head: 'vclerc:feature/automated_versions_bump',
              base: 'main'
            });
            
            if (res.data.length === 0) {
              await github.rest.pulls.create({
                owner: 'vclerc',
                repo: 'console-printer-lerna',
                title: 'Testing PR creation',
                head: 'feature/automated_versions_bump',
                base: 'main'
              });
            }