on:
  workflow_call:
    inputs:
      targetVariable:
        description: Env variable to be update
        required: true
        type: string
      newValue:
        description: Value to be assigned to the targeted env variable
        required: true
        type: string

  repository_dispatch:
    types: version-bump

name: pr-creation
concurrency:
  group: version-bump
  cancel-in-progress: false

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ vars.HEAD_BRANCH }}

      - uses: actions/github-script@v6
        id: test
        if: github.event_name == 'workflow_dispatch'
        with:
          script: |
            console.log("YEAH !")

      - id: update-env
        env:
          FILE: test.env
        run: |
          sed -i 's/${{inputs.targetVariable}}=.*/${{inputs.targetVariable}}=${{inputs.newValue}}/' $FILE
          
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add .
          git commit -m "chore: bump default version for ${{inputs.targetVariable}} to ${{inputs.newValue}}"
          git push origin

      - uses: actions/github-script@v6
        id: open-pull-request
        with:
          script: |
            console.log("Test: " + "${{ github.event_name }}");
            let repo = '${{github.repository}}'.split('/')[1];
            let res = await github.rest.pulls.list({
              owner: '${{github.repository_owner}}',
              repo: repo,
              state: 'open',
              head: '${{github.repository_owner}}:${{vars.HEAD_BRANCH}}',
              base: '${{vars.BASE_BRANCH}}'
            });
            
            if (res.data.length === 0) {
              await github.rest.pulls.create({
                owner: '${{github.repository_owner}}',
                repo: repo,
                title: 'Updating services default version',
                head: '${{vars.HEAD_BRANCH}}',
                base: '${{vars.BASE_BRANCH}}'
              });
            }