on:
  push:
    branches:
      - main
      - 'support/**'

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          default-branch: ${{ github.ref_name }}
          command: manifest
