on:
  push:
    branches:
      - main
      - 'release/**'

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.5.0
        id: release
        with:
          default-branch: ${{ github.ref_name }}
          command: manifest
      - name: Set current date
        id: set_date
        run: echo "::set-output name=date::$(date + '%Y-%m-%d')"
      - name: Test reading output
        id: read_output
        run: echo release_created ${{ toJSON(steps.set_date.outputs.date) }}
      - uses: actions/github-script@v6
        name: create release branch
        id: create-stable
        if: ${{ steps.release_step.outputs.release_created && github.ref_name == 'main' }}
        with:
          script: |
            await github.res.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/heads/release/${{ steps.set_date.outputs.date }}",
              sha: '${{ steps.release.outputs.sha }}'
            });
