on:
  workflow_dispatch:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          target-branch: ${{ github.ref_name }}
          manifest-file: .release-please-manifest.json
