on:
  push:
    branches:
      - main
      - 'release/**'

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3.5.0
        id: release
        with:
          default-branch: ${{ github.ref_name }}
          command: manifest
      - name: Test Outputs
        id: test_output
        run: echo "::set-output name=FOO::BAR"
      - name: Test reading output
        id: read_output
        run: echo Test ${{ toJSON(steps.test_ouptut.outputs) }}
      - name: Release-please outputs
        run: |
          echo release_created ${{ toJSON(steps.release.outputs.release_created) }}
          echo major ${{ toJSON(steps.release.outputs.major) }}
          echo minor ${{ toJSON(steps.release.outputs.minor) }}
          echo branch ${{ toJSON(github.ref_name) }}
      - uses: actions/github-script@v6
        name: create release branch
        id: create-stable
        if: ${{ steps.release.outputs.release_created && github.ref_name == 'main' }}
        with:
          script: |
            await github.res.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/heads/release/${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}",
              sha: '${{ steps.release.outputs.sha }}'
            });
