name: Tag/Branch distinction on workflow dispatch

on:
  workflow_dispatch:

jobs:
  get-tag:
    name: Get Tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: print actions info
        uses: actions/github-script@v6
        with:
          script: |
            console.log('+++++++++++++++++++++++++++++++++++++++++');
            console.log(`github.event: ${JSON.stringify(github.event, null, 4)}`);
            console.log(`github.event: ${JSON.stringify(github.event_name, null, 4)}`);
            console.log('+++++++++++++++++++++++++++++++++++++++++');
      - name: Set Push Tag Suffix
        id: push-tag-suffix
        if: ${{ false }}
        run: |
          # Add Push Tag Suffix to ENV
          echo "PUSH_TAG_SUFFIX=-${GITHUB_SHA:0:8}" >> "$GITHUB_OUTPUT"
      - name: Set Push Tag
        id: push-tag
        if: ${{ false }}
        env:
          PUSH_TAG_SUFFIX: ${{ steps.push-tag-suffix.outputs.PUSH_TAG_SUFFIX }}
        run: |
          # Add Push Tag to ENV
          VERSION=`node -e "process.stdout.write(require('./packages/package.json').version)"`
          echo "PUSH_TAG=${VERSION}${PUSH_TAG_SUFFIX}" >> "$GITHUB_OUTPUT"